version: '3.7'
services:
  testing-smarthome-mariadb:
    image: mariadb
    container_name: smarthome-mariadb-testing
    hostname: smarthome-db-testing
    environment:
      - MYSQL_ROOT_PASSWORD=testing
      - MARIADB_ROOT_PASSWORD=testing
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=smarthome
      - MYSQL_USER=smarthome
      - MYSQL_PASSWORD=testing
    ports:
      - 3330:3306
    restart: unless-stopped
    volumes:
      - testing-data:/var/lib/mysql

volumes:
  testing-data:
